Document: siparmyknife
Title: Debian siparmyknife Manual
Author: <insert document author here>
Abstract: This manual describes what siparmyknife is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/siparmyknife/siparmyknife.sgml.gz

Format: postscript
Files: /usr/share/doc/siparmyknife/siparmyknife.ps.gz

Format: text
Files: /usr/share/doc/siparmyknife/siparmyknife.text.gz

Format: HTML
Index: /usr/share/doc/siparmyknife/html/index.html
Files: /usr/share/doc/siparmyknife/html/*.html
